//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlsLibrary.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ControlsLibrary.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string downvoteIconButtonTooltip {
            get {
                return ResourceManager.GetString("downvoteIconButtonTooltip", resourceCulture);
            }
        }
        
        internal static string upvoteIconButtonTooltip {
            get {
                return ResourceManager.GetString("upvoteIconButtonTooltip", resourceCulture);
            }
        }
        
        internal static string searchBarHintText {
            get {
                return ResourceManager.GetString("searchBarHintText", resourceCulture);
            }
        }
        
        internal static string searchBarLabelText {
            get {
                return ResourceManager.GetString("searchBarLabelText", resourceCulture);
            }
        }
        
        internal static string shareIconButtonTooltip {
            get {
                return ResourceManager.GetString("shareIconButtonTooltip", resourceCulture);
            }
        }
        
        internal static string favoriteIconButtonTooltip {
            get {
                return ResourceManager.GetString("favoriteIconButtonTooltip", resourceCulture);
            }
        }
        
        internal static string exceptionIndicatorGenericTitle {
            get {
                return ResourceManager.GetString("exceptionIndicatorGenericTitle", resourceCulture);
            }
        }
        
        internal static string exceptionIndicatorTryAgainButton {
            get {
                return ResourceManager.GetString("exceptionIndicatorTryAgainButton", resourceCulture);
            }
        }
        
        internal static string exceptionIndicatorGenericMessage {
            get {
                return ResourceManager.GetString("exceptionIndicatorGenericMessage", resourceCulture);
            }
        }
        
        internal static string genericErrorSnackbarMessage {
            get {
                return ResourceManager.GetString("genericErrorSnackbarMessage", resourceCulture);
            }
        }
        
        internal static string authenticationRequiredErrorSnackbarMessage {
            get {
                return ResourceManager.GetString("authenticationRequiredErrorSnackbarMessage", resourceCulture);
            }
        }
    }
}
