//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignIn.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SignIn.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string invalidCredentialsErrorMessage {
            get {
                return ResourceManager.GetString("invalidCredentialsErrorMessage", resourceCulture);
            }
        }
        
        internal static string appBarTitle {
            get {
                return ResourceManager.GetString("appBarTitle", resourceCulture);
            }
        }
        
        internal static string emailTextFieldLabel {
            get {
                return ResourceManager.GetString("emailTextFieldLabel", resourceCulture);
            }
        }
        
        internal static string emailTextFieldEmptyErrorMessage {
            get {
                return ResourceManager.GetString("emailTextFieldEmptyErrorMessage", resourceCulture);
            }
        }
        
        internal static string emailTextFieldInvalidErrorMessage {
            get {
                return ResourceManager.GetString("emailTextFieldInvalidErrorMessage", resourceCulture);
            }
        }
        
        internal static string passwordTextFieldLabel {
            get {
                return ResourceManager.GetString("passwordTextFieldLabel", resourceCulture);
            }
        }
        
        internal static string passwordTextFieldEmptyErrorMessage {
            get {
                return ResourceManager.GetString("passwordTextFieldEmptyErrorMessage", resourceCulture);
            }
        }
        
        internal static string passwordTextFieldInvalidErrorMessage {
            get {
                return ResourceManager.GetString("passwordTextFieldInvalidErrorMessage", resourceCulture);
            }
        }
        
        internal static string forgotMyPasswordButtonLabel {
            get {
                return ResourceManager.GetString("forgotMyPasswordButtonLabel", resourceCulture);
            }
        }
        
        internal static string signInButtonLabel {
            get {
                return ResourceManager.GetString("signInButtonLabel", resourceCulture);
            }
        }
        
        internal static string signUpOpeningText {
            get {
                return ResourceManager.GetString("signUpOpeningText", resourceCulture);
            }
        }
        
        internal static string signUpButtonLabel {
            get {
                return ResourceManager.GetString("signUpButtonLabel", resourceCulture);
            }
        }
    }
}
