//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileMenu.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ProfileMenu.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string signInButtonLabel {
            get {
                return ResourceManager.GetString("signInButtonLabel", resourceCulture);
            }
        }
        
        internal static string signedInUserGreeting {
            get {
                return ResourceManager.GetString("signedInUserGreeting", resourceCulture);
            }
        }
        
        internal static string updateProfileTileLabel {
            get {
                return ResourceManager.GetString("updateProfileTileLabel", resourceCulture);
            }
        }
        
        internal static string darkModePreferencesHeaderTileLabel {
            get {
                return ResourceManager.GetString("darkModePreferencesHeaderTileLabel", resourceCulture);
            }
        }
        
        internal static string darkModePreferencesAlwaysDarkTileLabel {
            get {
                return ResourceManager.GetString("darkModePreferencesAlwaysDarkTileLabel", resourceCulture);
            }
        }
        
        internal static string darkModePreferencesAlwaysLightTileLabel {
            get {
                return ResourceManager.GetString("darkModePreferencesAlwaysLightTileLabel", resourceCulture);
            }
        }
        
        internal static string darkModePreferencesUseSystemSettingsTileLabel {
            get {
                return ResourceManager.GetString("darkModePreferencesUseSystemSettingsTileLabel", resourceCulture);
            }
        }
        
        internal static string signOutButtonLabel {
            get {
                return ResourceManager.GetString("signOutButtonLabel", resourceCulture);
            }
        }
        
        internal static string signUpOpeningText {
            get {
                return ResourceManager.GetString("signUpOpeningText", resourceCulture);
            }
        }
        
        internal static string signUpButtonLabel {
            get {
                return ResourceManager.GetString("signUpButtonLabel", resourceCulture);
            }
        }
    }
}
