namespace QuotesApi;

public static class LocalApi
{
    public static Task<string> GetAsync()
    {
        return Task.FromResult(@"
{
    ""page"": 1,
    ""last_page"": false,
    ""quotes"": [
    {
        ""id"": 6879,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""best""],
        ""url"": ""https://favqs.com/quotes/michael-jordan/6879-the-best-evalu-"",
        ""favorites_count"": 1,
        ""upvotes_count"": 2,
        ""downvotes_count"": 0,
        ""author"": ""Michael Jordan"",
        ""author_permalink"": ""michael-jordan"",
        ""body"": ""The best evaluation I can make of a player is to look in his eyes and see how scared they are.""
    },
    {
        ""id"": 62759,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [],
        ""url"": ""https://favqs.com/quotes/ayush-patel/62759-nxxjdjdhs"",
        ""favorites_count"": 2,
        ""upvotes_count"": 0,
        ""downvotes_count"": 0,
        ""author"": ""Ayush Patel"",
        ""author_permalink"": ""ayush-patel"",
        ""body"": ""Nxxjdjdhs""
    },
    {
        ""id"": 410,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""religion"", ""american"", ""deaf"", ""blind"", ""author""],
        ""url"": ""https://favqs.com/quotes/helen-keller/410-i-am-a-child-of-"",
        ""favorites_count"": 3,
        ""upvotes_count"": 1,
        ""downvotes_count"": 0,
        ""author"": ""Helen Keller"",
        ""author_permalink"": ""helen-keller"",
        ""body"": ""I am a child of God, an inheritor of a fragment of the mind that created all worlds.""
    },
    {
        ""id"": 36300,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""leadership"", ""success""],
        ""url"": ""https://favqs.com/quotes/dwight-d-eisenhower/36300-the-supreme-q-"",
        ""favorites_count"": 0,
        ""upvotes_count"": 2,
        ""downvotes_count"": 0,
        ""author"": ""Dwight D. Eisenhower"",
        ""author_permalink"": ""dwight-d-eisenhower"",
        ""body"": ""The supreme quality for leadership is unquestionably integrity. Without it, no real success is possible, no matter whether it is on a section gang, a football field, in an army, or in an office.""
    },
    {
        ""id"": 61936,
        ""dialogue"": false,
        ""source"": ""https://twitter.com/pmarca/status/510486200776290305"",
        ""private"": false,
        ""tags"": [""startup"", ""entrepreneur"", ""failing"", ""success""],
        ""url"": ""https://favqs.com/quotes/marc-andreessen/61936-my-goal-is-no-"",
        ""favorites_count"": 3,
        ""upvotes_count"": 1,
        ""downvotes_count"": 0,
        ""author"": ""Marc Andreessen"",
        ""author_permalink"": ""marc-andreessen"",
        ""body"": ""My goal is not to fail fast. My goal is to succeed over the long run. They are not the same thing.""
    },
    {
        ""id"": 31501,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""history""],
        ""url"": ""https://favqs.com/quotes/henry-ford/31501-we-don-t-want-"",
        ""favorites_count"": 3,
        ""upvotes_count"": 2,
        ""downvotes_count"": 0,
        ""author"": ""Henry Ford"",
        ""author_permalink"": ""henry-ford"",
        ""body"": ""We don't want tradition. We want to live in the present and the only history that is worth a tinker's dam is the history we make today.""
    },
    {
        ""id"": 364,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""goals""],
        ""url"": ""https://favqs.com/quotes/henry-wadsworth-longfellow/364-if-you-would-hi-"",
        ""favorites_count"": 3,
        ""upvotes_count"": 1,
        ""downvotes_count"": 0,
        ""author"": ""Henry Wadsworth Longfellow"",
        ""author_permalink"": ""henry-wadsworth-longfellow"",
        ""body"": ""If you would hit the mark, you must aim a little above it.""
    },
    {
        ""id"": 18309,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""failure"", ""god""],
        ""url"": ""https://favqs.com/quotes/h-l-mencken/18309-the-theory-se-"",
        ""favorites_count"": 2,
        ""upvotes_count"": 1,
        ""downvotes_count"": 0,
        ""author"": ""H. L. Mencken"",
        ""author_permalink"": ""h-l-mencken"",
        ""body"": ""The theory seems to be that as long as a man is a failure he is one of God's children, but that as soon as he succeeds he is taken over by the Devil.""
    },
    {
        ""id"": 45451,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""patience""],
        ""url"": ""https://favqs.com/quotes/arnold-h-glasow/45451-the-key-to-ev-"",
        ""favorites_count"": 2,
        ""upvotes_count"": 1,
        ""downvotes_count"": 0,
        ""author"": ""Arnold H. Glasow"",
        ""author_permalink"": ""arnold-h-glasow"",
        ""body"": ""The key to everything is patience. You get the chicken by hatching the egg, not by smashing it.""
    },
    {
        ""id"": 27937,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""good""],
        ""url"": ""https://favqs.com/quotes/john-mayer/27937-ladies-if-you-"",
        ""favorites_count"": 2,
        ""upvotes_count"": 1,
        ""downvotes_count"": 0,
        ""author"": ""John Mayer"",
        ""author_permalink"": ""john-mayer"",
        ""body"": ""Ladies, if you want to know the way to my heart... good spelling and good grammar, good punctuation, capitalize only where you are supposed to capitalize, it's done.""
    },
    {
        ""id"": 62529,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [],
        ""url"": ""https://favqs.com/quotes/marcus-aurelius/62529-very-little-i-"",
        ""favorites_count"": 2,
        ""upvotes_count"": 0,
        ""downvotes_count"": 0,
        ""author"": ""Marcus Aurelius"",
        ""author_permalink"": ""marcus-aurelius"",
        ""body"": ""Very little is needed to make a happy life; it is all within yourself, in your way of thinking.""
    },
    {
        ""id"": 449,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""programming"", ""debugging""],
        ""url"": ""https://favqs.com/quotes/brian-kernighan/449-debugging-is-tw-"",
        ""favorites_count"": 2,
        ""upvotes_count"": 0,
        ""downvotes_count"": 0,
        ""author"": ""Brian Kernighan"",
        ""author_permalink"": ""brian-kernighan"",
        ""body"": ""Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.""
    },
    {
        ""id"": 64006,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [],
        ""url"": ""https://favqs.com/quotes/hp/64006-test"",
        ""favorites_count"": 2,
        ""upvotes_count"": 0,
        ""downvotes_count"": 0,
        ""author"": ""hp"",
        ""author_permalink"": ""hp"",
        ""body"": ""test""
    },
    {
        ""id"": 57493,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""travel""],
        ""url"": ""https://favqs.com/quotes/gilbert-k-chesterton/57493-the-traveler--"",
        ""favorites_count"": 3,
        ""upvotes_count"": 1,
        ""downvotes_count"": 0,
        ""author"": ""Gilbert K. Chesterton"",
        ""author_permalink"": ""gilbert-k-chesterton"",
        ""body"": ""The traveler sees what he sees, the tourist sees what he has come to see.""
    },
    {
        ""id"": 64871,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [],
        ""url"": ""https://favqs.com/quotes/author150550/64871-body478880"",
        ""favorites_count"": 2,
        ""upvotes_count"": 0,
        ""downvotes_count"": 1,
        ""author"": ""Author150550"",
        ""author_permalink"": ""author150550"",
        ""body"": ""body478880""
    },
    {
        ""id"": 41887,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""money""],
        ""url"": ""https://favqs.com/quotes/bob-hope/41887-i-have-too-mu-"",
        ""favorites_count"": 0,
        ""upvotes_count"": 2,
        ""downvotes_count"": 0,
        ""author"": ""Bob Hope"",
        ""author_permalink"": ""bob-hope"",
        ""body"": ""I have too much money invested in sweaters.""
    },
    {
        ""id"": 21622,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""fear"", ""great"", ""leadership"", ""respect""],
        ""url"": ""https://favqs.com/quotes/yousef-munayyer/21622-humility-is-a-"",
        ""favorites_count"": 2,
        ""upvotes_count"": 0,
        ""downvotes_count"": 0,
        ""author"": ""Yousef Munayyer"",
        ""author_permalink"": ""yousef-munayyer"",
        ""body"": ""Humility is a great quality of leadership which derives respect and not just fear or hatred.""
    },
    {
        ""id"": 592,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""love"", ""british"", ""poet"", ""loss""],
        ""url"": ""https://favqs.com/quotes/alfred-tennyson/592-tis-better-to-h-"",
        ""favorites_count"": 8,
        ""upvotes_count"": 2,
        ""downvotes_count"": 0,
        ""author"": ""Alfred Tennyson"",
        ""author_permalink"": ""alfred-tennyson"",
        ""body"": ""Tis better to have loved and lost.\r\u003cbr\u003eThan never to have loved at all.""
    },
    {
        ""id"": 24303,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""friendship""],
        ""url"": ""https://favqs.com/quotes/ralph-waldo-emerson/24303-the-only-way--"",
        ""favorites_count"": 2,
        ""upvotes_count"": 2,
        ""downvotes_count"": 0,
        ""author"": ""Ralph Waldo Emerson"",
        ""author_permalink"": ""ralph-waldo-emerson"",
        ""body"": ""The only way to have a friend is to be one.""
    },
    {
        ""id"": 26658,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""god""],
        ""url"": ""https://favqs.com/quotes/friedrich-nietzsche/26658-i-would-belie-"",
        ""favorites_count"": 4,
        ""upvotes_count"": 1,
        ""downvotes_count"": 0,
        ""author"": ""Friedrich Nietzsche"",
        ""author_permalink"": ""friedrich-nietzsche"",
        ""body"": ""I would believe only in a God that knows how to Dance.""
    },
    {
        ""id"": 62480,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [],
        ""url"": ""https://favqs.com/quotes/diogenes-of-sinope/62480-wise-leaders--"",
        ""favorites_count"": 2,
        ""upvotes_count"": 1,
        ""downvotes_count"": 0,
        ""author"": ""Diogenes of Sinope"",
        ""author_permalink"": ""diogenes-of-sinope"",
        ""body"": ""Wise leaders generally have wise counselors because it takes a wise person themselves to distinguish them.""
    },
    {
        ""id"": 4119,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""architecture"", ""imagination""],
        ""url"": ""https://favqs.com/quotes/gilbert-k-chesterton/4119-there-are-no-r-"",
        ""favorites_count"": 2,
        ""upvotes_count"": 1,
        ""downvotes_count"": 0,
        ""author"": ""Gilbert K. Chesterton"",
        ""author_permalink"": ""gilbert-k-chesterton"",
        ""body"": ""There are no rules of architecture for a castle in the clouds.""
    },
    {
        ""id"": 38313,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""life""],
        ""url"": ""https://favqs.com/quotes/aldous-huxley/38313-it-is-a-bit-e-"",
        ""favorites_count"": 1,
        ""upvotes_count"": 3,
        ""downvotes_count"": 0,
        ""author"": ""Aldous Huxley"",
        ""author_permalink"": ""aldous-huxley"",
        ""body"": ""It is a bit embarrassing to have been concerned with the human problem all one's life and find at the end that one has no more to offer by way of advice than 'try to be a little kinder.'""
    },
    {
        ""id"": 45485,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""patience""],
        ""url"": ""https://favqs.com/quotes/ambrose-bierce/45485-meekness-unco-"",
        ""favorites_count"": 1,
        ""upvotes_count"": 2,
        ""downvotes_count"": 0,
        ""author"": ""Ambrose Bierce"",
        ""author_permalink"": ""ambrose-bierce"",
        ""body"": ""Meekness: Uncommon patience in planning a revenge that is worth while.""
    },
    {
        ""id"": 60589,
        ""dialogue"": false,
        ""private"": false,
        ""tags"": [""women""],
        ""url"": ""https://favqs.com/quotes/sophocles/60589-silence-is-an-"",
        ""favorites_count"": 1,
        ""upvotes_count"": 2,
        ""downvotes_count"": 0,
        ""author"": ""Sophocles"",
        ""author_permalink"": ""sophocles"",
        ""body"": ""Silence is an ornament for women.""
    }]
}
");
    }
}