//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForgotMyPassword.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_pt {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_pt() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ForgotMyPassword.Resources.Resources_pt", typeof(Resources_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string dialogTitle {
            get {
                return ResourceManager.GetString("dialogTitle", resourceCulture);
            }
        }
        
        internal static string emailTextFieldLabel {
            get {
                return ResourceManager.GetString("emailTextFieldLabel", resourceCulture);
            }
        }
        
        internal static string emailTextFieldEmptyErrorMessage {
            get {
                return ResourceManager.GetString("emailTextFieldEmptyErrorMessage", resourceCulture);
            }
        }
        
        internal static string emailTextFieldInvalidErrorMessage {
            get {
                return ResourceManager.GetString("emailTextFieldInvalidErrorMessage", resourceCulture);
            }
        }
        
        internal static string confirmButtonLabel {
            get {
                return ResourceManager.GetString("confirmButtonLabel", resourceCulture);
            }
        }
        
        internal static string cancelButtonLabel {
            get {
                return ResourceManager.GetString("cancelButtonLabel", resourceCulture);
            }
        }
        
        internal static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        internal static string emailRequestSuccessMessage {
            get {
                return ResourceManager.GetString("emailRequestSuccessMessage", resourceCulture);
            }
        }
    }
}
