//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteList.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("QuoteList.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string quoteListRefreshErrorMessage {
            get {
                return ResourceManager.GetString("quoteListRefreshErrorMessage", resourceCulture);
            }
        }
        
        internal static string favoritesTagLabel {
            get {
                return ResourceManager.GetString("favoritesTagLabel", resourceCulture);
            }
        }
        
        internal static string lifeTagLabel {
            get {
                return ResourceManager.GetString("lifeTagLabel", resourceCulture);
            }
        }
        
        internal static string happinessTagLabel {
            get {
                return ResourceManager.GetString("happinessTagLabel", resourceCulture);
            }
        }
        
        internal static string workTagLabel {
            get {
                return ResourceManager.GetString("workTagLabel", resourceCulture);
            }
        }
        
        internal static string natureTagLabel {
            get {
                return ResourceManager.GetString("natureTagLabel", resourceCulture);
            }
        }
        
        internal static string scienceTagLabel {
            get {
                return ResourceManager.GetString("scienceTagLabel", resourceCulture);
            }
        }
        
        internal static string loveTagLabel {
            get {
                return ResourceManager.GetString("loveTagLabel", resourceCulture);
            }
        }
        
        internal static string funnyTagLabel {
            get {
                return ResourceManager.GetString("funnyTagLabel", resourceCulture);
            }
        }
    }
}
